name = "spino-gambinobonus-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spino-gambinobonus.com.es"
HMAC_KEY = "501763a5ecf228bd84f65dc480ca6ce3541c6f5a78a7d2a7ec5382423200ca5c"
COOKIE_NAME = "5y8"
PLAY_PATH = "launch"
BUTTON_ID = "pfbed9fd6beb9b3ea35cd662711bcfd4a"
GATE_SALT = "4a9c0c2602ad1f48"
